// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type GameRooms = {
  roomId: string,
  templateId: string,
  hostId: Identity,
  currentPlayers: number,
  maxPlayers: number,
  status: string,
  createdAt: Timestamp,
  startedAt: Timestamp | undefined,
  endsAt: Timestamp | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameRooms {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("roomId", AlgebraicType.createStringType()),
      new ProductTypeElement("templateId", AlgebraicType.createStringType()),
      new ProductTypeElement("hostId", AlgebraicType.createIdentityType()),
      new ProductTypeElement("currentPlayers", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxPlayers", AlgebraicType.createI32Type()),
      new ProductTypeElement("status", AlgebraicType.createStringType()),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
      new ProductTypeElement("startedAt", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
      new ProductTypeElement("endsAt", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameRooms): void {
    GameRooms.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameRooms {
    return GameRooms.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


