// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type ProcessAiResponse = {
  messageId: bigint,
  aiResponse: string,
  vulnerabilityTriggered: string | undefined,
  secretLeaked: boolean,
  severityScore: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ProcessAiResponse {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("messageId", AlgebraicType.createU64Type()),
      new ProductTypeElement("aiResponse", AlgebraicType.createStringType()),
      new ProductTypeElement("vulnerabilityTriggered", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("secretLeaked", AlgebraicType.createBoolType()),
      new ProductTypeElement("severityScore", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ProcessAiResponse): void {
    ProcessAiResponse.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ProcessAiResponse {
    return ProcessAiResponse.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

