// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { CreateRoom } from "./create_room_reducer.ts";
export { CreateRoom };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { JoinRoom } from "./join_room_reducer.ts";
export { JoinRoom };
import { ProcessAiResponse } from "./process_ai_response_reducer.ts";
export { ProcessAiResponse };
import { SendAttackMessage } from "./send_attack_message_reducer.ts";
export { SendAttackMessage };
import { SetUsername } from "./set_username_reducer.ts";
export { SetUsername };
import { UpdateRoomLeaderboard } from "./update_room_leaderboard_reducer.ts";
export { UpdateRoomLeaderboard };

// Import and reexport all table handle types
import { AiRepliesTableHandle } from "./ai_replies_table.ts";
export { AiRepliesTableHandle };
import { GameResultTableHandle } from "./game_result_table.ts";
export { GameResultTableHandle };
import { GameRoomsTableHandle } from "./game_rooms_table.ts";
export { GameRoomsTableHandle };
import { LeaderboardTableHandle } from "./leaderboard_table.ts";
export { LeaderboardTableHandle };
import { MessagesTableHandle } from "./messages_table.ts";
export { MessagesTableHandle };
import { RoomPlayersTableHandle } from "./room_players_table.ts";
export { RoomPlayersTableHandle };
import { RoomTemplateTableHandle } from "./room_template_table.ts";
export { RoomTemplateTableHandle };
import { UsersTableHandle } from "./users_table.ts";
export { UsersTableHandle };

// Import and reexport all types
import { AiReplies } from "./ai_replies_type.ts";
export { AiReplies };
import { GameResult } from "./game_result_type.ts";
export { GameResult };
import { GameRooms } from "./game_rooms_type.ts";
export { GameRooms };
import { Leaderboard } from "./leaderboard_type.ts";
export { Leaderboard };
import { Messages } from "./messages_type.ts";
export { Messages };
import { RoomPlayers } from "./room_players_type.ts";
export { RoomPlayers };
import { RoomTemplate } from "./room_template_type.ts";
export { RoomTemplate };
import { Users } from "./users_type.ts";
export { Users };

const REMOTE_MODULE = {
  tables: {
    ai_replies: {
      tableName: "ai_replies",
      rowType: AiReplies.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: AiReplies.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    game_result: {
      tableName: "game_result",
      rowType: GameResult.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: GameResult.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    game_rooms: {
      tableName: "game_rooms",
      rowType: GameRooms.getTypeScriptAlgebraicType(),
      primaryKey: "roomId",
      primaryKeyInfo: {
        colName: "roomId",
        colType: GameRooms.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    leaderboard: {
      tableName: "leaderboard",
      rowType: Leaderboard.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Leaderboard.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    messages: {
      tableName: "messages",
      rowType: Messages.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Messages.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    room_players: {
      tableName: "room_players",
      rowType: RoomPlayers.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: RoomPlayers.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    room_template: {
      tableName: "room_template",
      rowType: RoomTemplate.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: RoomTemplate.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    users: {
      tableName: "users",
      rowType: Users.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Users.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    create_room: {
      reducerName: "create_room",
      argsType: CreateRoom.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    join_room: {
      reducerName: "join_room",
      argsType: JoinRoom.getTypeScriptAlgebraicType(),
    },
    process_ai_response: {
      reducerName: "process_ai_response",
      argsType: ProcessAiResponse.getTypeScriptAlgebraicType(),
    },
    send_attack_message: {
      reducerName: "send_attack_message",
      argsType: SendAttackMessage.getTypeScriptAlgebraicType(),
    },
    set_username: {
      reducerName: "set_username",
      argsType: SetUsername.getTypeScriptAlgebraicType(),
    },
    update_room_leaderboard: {
      reducerName: "update_room_leaderboard",
      argsType: UpdateRoomLeaderboard.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.3.2",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CreateRoom", args: CreateRoom }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "JoinRoom", args: JoinRoom }
| { name: "ProcessAiResponse", args: ProcessAiResponse }
| { name: "SendAttackMessage", args: SendAttackMessage }
| { name: "SetUsername", args: SetUsername }
| { name: "UpdateRoomLeaderboard", args: UpdateRoomLeaderboard }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  createRoom(templateId: string, maxPlayers: number) {
    const __args = { templateId, maxPlayers };
    let __writer = new BinaryWriter(1024);
    CreateRoom.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_room", __argsBuffer, this.setCallReducerFlags.createRoomFlags);
  }

  onCreateRoom(callback: (ctx: ReducerEventContext, templateId: string, maxPlayers: number) => void) {
    this.connection.onReducer("create_room", callback);
  }

  removeOnCreateRoom(callback: (ctx: ReducerEventContext, templateId: string, maxPlayers: number) => void) {
    this.connection.offReducer("create_room", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  joinRoom(roomId: string) {
    const __args = { roomId };
    let __writer = new BinaryWriter(1024);
    JoinRoom.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_room", __argsBuffer, this.setCallReducerFlags.joinRoomFlags);
  }

  onJoinRoom(callback: (ctx: ReducerEventContext, roomId: string) => void) {
    this.connection.onReducer("join_room", callback);
  }

  removeOnJoinRoom(callback: (ctx: ReducerEventContext, roomId: string) => void) {
    this.connection.offReducer("join_room", callback);
  }

  processAiResponse(messageId: bigint, aiResponse: string, vulnerabilityTriggered: string | undefined, secretLeaked: boolean, severityScore: number) {
    const __args = { messageId, aiResponse, vulnerabilityTriggered, secretLeaked, severityScore };
    let __writer = new BinaryWriter(1024);
    ProcessAiResponse.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("process_ai_response", __argsBuffer, this.setCallReducerFlags.processAiResponseFlags);
  }

  onProcessAiResponse(callback: (ctx: ReducerEventContext, messageId: bigint, aiResponse: string, vulnerabilityTriggered: string | undefined, secretLeaked: boolean, severityScore: number) => void) {
    this.connection.onReducer("process_ai_response", callback);
  }

  removeOnProcessAiResponse(callback: (ctx: ReducerEventContext, messageId: bigint, aiResponse: string, vulnerabilityTriggered: string | undefined, secretLeaked: boolean, severityScore: number) => void) {
    this.connection.offReducer("process_ai_response", callback);
  }

  sendAttackMessage(roomId: string, attackText: string) {
    const __args = { roomId, attackText };
    let __writer = new BinaryWriter(1024);
    SendAttackMessage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("send_attack_message", __argsBuffer, this.setCallReducerFlags.sendAttackMessageFlags);
  }

  onSendAttackMessage(callback: (ctx: ReducerEventContext, roomId: string, attackText: string) => void) {
    this.connection.onReducer("send_attack_message", callback);
  }

  removeOnSendAttackMessage(callback: (ctx: ReducerEventContext, roomId: string, attackText: string) => void) {
    this.connection.offReducer("send_attack_message", callback);
  }

  setUsername(username: string) {
    const __args = { username };
    let __writer = new BinaryWriter(1024);
    SetUsername.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_username", __argsBuffer, this.setCallReducerFlags.setUsernameFlags);
  }

  onSetUsername(callback: (ctx: ReducerEventContext, username: string) => void) {
    this.connection.onReducer("set_username", callback);
  }

  removeOnSetUsername(callback: (ctx: ReducerEventContext, username: string) => void) {
    this.connection.offReducer("set_username", callback);
  }

  updateRoomLeaderboard(roomId: string, userId: Identity, newScore: number) {
    const __args = { roomId, userId, newScore };
    let __writer = new BinaryWriter(1024);
    UpdateRoomLeaderboard.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_room_leaderboard", __argsBuffer, this.setCallReducerFlags.updateRoomLeaderboardFlags);
  }

  onUpdateRoomLeaderboard(callback: (ctx: ReducerEventContext, roomId: string, userId: Identity, newScore: number) => void) {
    this.connection.onReducer("update_room_leaderboard", callback);
  }

  removeOnUpdateRoomLeaderboard(callback: (ctx: ReducerEventContext, roomId: string, userId: Identity, newScore: number) => void) {
    this.connection.offReducer("update_room_leaderboard", callback);
  }

}

export class SetReducerFlags {
  createRoomFlags: CallReducerFlags = 'FullUpdate';
  createRoom(flags: CallReducerFlags) {
    this.createRoomFlags = flags;
  }

  joinRoomFlags: CallReducerFlags = 'FullUpdate';
  joinRoom(flags: CallReducerFlags) {
    this.joinRoomFlags = flags;
  }

  processAiResponseFlags: CallReducerFlags = 'FullUpdate';
  processAiResponse(flags: CallReducerFlags) {
    this.processAiResponseFlags = flags;
  }

  sendAttackMessageFlags: CallReducerFlags = 'FullUpdate';
  sendAttackMessage(flags: CallReducerFlags) {
    this.sendAttackMessageFlags = flags;
  }

  setUsernameFlags: CallReducerFlags = 'FullUpdate';
  setUsername(flags: CallReducerFlags) {
    this.setUsernameFlags = flags;
  }

  updateRoomLeaderboardFlags: CallReducerFlags = 'FullUpdate';
  updateRoomLeaderboard(flags: CallReducerFlags) {
    this.updateRoomLeaderboardFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get aiReplies(): AiRepliesTableHandle {
    return new AiRepliesTableHandle(this.connection.clientCache.getOrCreateTable<AiReplies>(REMOTE_MODULE.tables.ai_replies));
  }

  get gameResult(): GameResultTableHandle {
    return new GameResultTableHandle(this.connection.clientCache.getOrCreateTable<GameResult>(REMOTE_MODULE.tables.game_result));
  }

  get gameRooms(): GameRoomsTableHandle {
    return new GameRoomsTableHandle(this.connection.clientCache.getOrCreateTable<GameRooms>(REMOTE_MODULE.tables.game_rooms));
  }

  get leaderboard(): LeaderboardTableHandle {
    return new LeaderboardTableHandle(this.connection.clientCache.getOrCreateTable<Leaderboard>(REMOTE_MODULE.tables.leaderboard));
  }

  get messages(): MessagesTableHandle {
    return new MessagesTableHandle(this.connection.clientCache.getOrCreateTable<Messages>(REMOTE_MODULE.tables.messages));
  }

  get roomPlayers(): RoomPlayersTableHandle {
    return new RoomPlayersTableHandle(this.connection.clientCache.getOrCreateTable<RoomPlayers>(REMOTE_MODULE.tables.room_players));
  }

  get roomTemplate(): RoomTemplateTableHandle {
    return new RoomTemplateTableHandle(this.connection.clientCache.getOrCreateTable<RoomTemplate>(REMOTE_MODULE.tables.room_template));
  }

  get users(): UsersTableHandle {
    return new UsersTableHandle(this.connection.clientCache.getOrCreateTable<Users>(REMOTE_MODULE.tables.users));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
