// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type Leaderboard = {
  id: bigint,
  roomId: string,
  userId: Identity,
  username: string,
  score: number,
  rank: number,
  extractionTime: number | undefined,
  updatedAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Leaderboard {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("roomId", AlgebraicType.createStringType()),
      new ProductTypeElement("userId", AlgebraicType.createIdentityType()),
      new ProductTypeElement("username", AlgebraicType.createStringType()),
      new ProductTypeElement("score", AlgebraicType.createI32Type()),
      new ProductTypeElement("rank", AlgebraicType.createI32Type()),
      new ProductTypeElement("extractionTime", AlgebraicType.createOptionType(AlgebraicType.createI32Type())),
      new ProductTypeElement("updatedAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Leaderboard): void {
    Leaderboard.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Leaderboard {
    return Leaderboard.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


